### ISSUE TITLE
NEED BETA TESTERS

### ISSUE THREAD

**Issue by ZombieTheBest** [ZombieTheBest/XPS9350-10.13-HighSierra#6]
Hello. 
I've noticed that the DSDT file created using original Deploy has errors when decompiled, so I edited the way the script applies Patches to prevent these errors. 

I need someone to test and report back if everything works. 

1. Download the files attached
2. Unzip and run Deploy.sh as usual. See if you get some errors. Copy the output in a txt file when it's done.
3. Attach your CLOVER folder and the output
4. Reboot and see if everything is working as usual (report issue if you have)
5. If you have some issues re-patch with stable Deploy

Thank you!
[XPS9350-10.13-HighSierra-BETA.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1430409/XPS9350-10.13-HighSierra-BETA.zip)

**Comment by chenyisen** [comment]
I've tried your beta deploy, and there are some issues. Here are feedbacks when run the deploy.
[FAILED]  Compile sensrhub.
Compiler aborting due to parser-detected syntax error(s)
/Users/chenyan/Downloads/XPS9350-10.13-HighSierra-BETA/DSDT/precompile/SSDT-1.dsl    101:                                 }
Error    6126 -                                                                             syntax error, unexpected '}' ^ 

/Users/chenyan/Downloads/XPS9350-10.13-HighSierra-BETA/DSDT/precompile/SSDT-1.dsl    122:                                 If (LGreater (DFUD, Zero))
Error    6126 -                                                                       syntax error, unexpected PARSEOP_IF ^ 

/Users/chenyan/Downloads/XPS9350-10.13-HighSierra-BETA/DSDT/precompile/SSDT-1.dsl    123:                                 {
Error    6126 -                                                                             syntax error, unexpected '{' ^ 

/Users/chenyan/Downloads/XPS9350-10.13-HighSierra-BETA/DSDT/precompile/SSDT-1.dsl    127:                                 }
Error    6126 -                                                                             syntax error, unexpected '}' ^ 

/Users/chenyan/Downloads/XPS9350-10.13-HighSierra-BETA/DSDT/precompile/SSDT-1.dsl    157: 
Error    6126 - syntax error, unexpected $end and premature End-Of-File

--------------------------------------------------------

[  OK  ]  Install Xhci table.
./Deploy.sh: line 2027: [0: command not found

--------------------------------------------------------

And the process will stop at "[  OK  ] Install VoodooPS2Controller"

**Comment by ZombieTheBest** [comment]
@chenyisen Thank you very much for your time! Please try this new version and let me know!

[XPS9350-10.13-HighSierra-BETA.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1433691/XPS9350-10.13-HighSierra-BETA.zip)

**Comment by ZombieTheBest** [comment]
Fixed the SSDT-1 Compile Error. That is caused by newer version of Clover. Credits @squash-
Please test this BETA Deploy. If it goes well this will be next commit. 👍 


1. Download the files attached
2. Unzip and run Deploy.sh as usual. See if you get some errors. Copy the output in a txt file when it's done.
3. Attach your CLOVER folder and the output
4. Reboot and see if everything is working as usual (report issue if you have)
    
If you have some issues re-patch with stable Deploy

Thank you again!

[XPS9350-10.13-HighSierra-BETA.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1435518/XPS9350-10.13-HighSierra-BETA.zip)

**Comment by ZombieTheBest** [comment]
Did it worked for you @chenyisen ?

**Comment by maz-1** [comment]
My result : Compilation finishes without errors. Almost every hardware(except thunderbolt port and sdcard reader) works.

**Comment by ZombieTheBest** [comment]
Perfect @maz-1 
Do you get any error if you decompile the DSDT.aml you get? What about if you do the same with the main branch?

Thank you again!

**Comment by ZombieTheBest** [comment]
Fixed some Deploy errors + Merged BETA with Master. Thank you all!
